### ISSUE TITLE
Reindeer meat can not be cooked

### ISSUE THREAD

**Issue by shanemd** [MultiCraft/MultiCraft_mods#109]
While playing Multicraft in Minetest world, it seems all meats can be cooked except reindeer. When placed in a furnace with fuel, it just doesn't do anything. This makes survival in winter biomes difficult. I expect this is an oversight or bug.

Multicraft reports version 2.0.9.

**Comment by MoNTE48** [comment]
Hello.
1) we do not support third-party games
2) as far as I know, there are no mobs in Minetest Game at all. 
You need to write to the authors of the game/modification you have a problem with.

**Comment by shanemd** [comment]
Thank you. I'll see if I can identify the mod that provides these Reindeer.
